
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igzpvqkfwttviddklyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnenB2cWtmd3R0dmlkZGtseXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTMzNTAsImV4cCI6MjA1OTI2OTM1MH0.jGnZ0kV-A8NBUMDFGAFyZxnvbRUHBXreQVqJqe8BxC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
